### ISSUE TITLE
Nothing Happens When Try To Sign Up With Odd credentials (like, literally nothing)

### ISSUE THREAD

**Issue by ifasoldt** [aoristdev/orderlyaid#59]
<img width="495" alt="screen shot 2017-04-20 at 9 21 11 pm" src="https://cloud.githubusercontent.com/assets/18588427/25258731/6622839e-260f-11e7-9a9a-7e93e47b50ab.png">

**Comment by davegregg** [comment]
Yes, we have validations on email address and phone number, neither of which passes the above. But we haven't yet implemented the error message. That is in the works! Thanks!

**Comment by ifasoldt** [comment]
<img width="479" alt="screen shot 2017-04-20 at 11 40 11 pm" src="https://cloud.githubusercontent.com/assets/18588427/25261931/d2f408c2-2622-11e7-9868-f1a772308fca.png">
Would like to test more, but can't seem to sign up no matter what I do.

**Comment by davegregg** [comment]
Yeah, okay I see your error. A relic of a model property we retired. We had a git collision this evening that initially we didn't understand and a few very recent changes got rewound as a consequence. I thought I caught all the backend tweaks I had previously made, but I missed this, so I'll fix it and then compare the current branch with one just prior to the collision, here in a few hours. Thanks! 









On Thu, Apr 20, 2017 at 11:41 PM -0400, "Isaiah Edward Fasoldt" <notifications@github.com> wrote:













Would like to test more, but can't seem to sign up no matter what I do.

**Comment by ifasoldt** [comment]
Ah, guess I caught you at a bad time. I'll be back later to test.

**Comment by davegregg** [comment]
Lots of bugs fixed, refactoring, etc. with the new update. This one included!
