### ISSUE TITLE
wrong date/time

### ISSUE THREAD

**Issue by jeffbum** [aoristdev/orderlyaid#76]
at https://orderlyaid.herokuapp.com/nav/profile/todaysmeds#currentMed0, the time and date for my next time to take my advil is wrong. 
<img width="834" alt="screen shot 2017-04-22 at 11 15 39 am" src="https://cloud.githubusercontent.com/assets/21953047/25305632/27551b60-274d-11e7-9420-440b80c1ac02.png">

**Comment by jeffbum** [comment]
The time is off as well above the cards in the middle. it was 11:15 am when I created it.

**Comment by strempe** [comment]
Add the new routes and now 'later today' shows the time and name of the user next medication!
