### ISSUE TITLE
Time Input Fields Aren't consistently styled.

### ISSUE THREAD

**Issue by ifasoldt** [aoristdev/orderlyaid#79]
<img width="424" alt="screen shot 2017-04-22 at 4 21 10 pm" src="https://cloud.githubusercontent.com/assets/18588427/25307915/ca93f04c-2777-11e7-9c76-5b2317801ae3.png">

**Comment by ifasoldt** [comment]
Specifically, the clock on one but not the other. Also, I thought the clock was a timepickr.

**Comment by strempe** [comment]
This has been fixed. We were testing different date/time pickers, none of which worked well :( 
Now they are all consistent fields with placeholder text to help the user!
