### ISSUE TITLE
[Validations] Hitting Next Breaks App

### ISSUE THREAD

**Issue by ifasoldt** [aoristdev/orderlyaid#81]
<img width="694" alt="screen shot 2017-04-22 at 4 23 23 pm" src="https://cloud.githubusercontent.com/assets/18588427/25307934/1cd4fd10-2778-11e7-9e2a-672614e4f316.png">

**Comment by strempe** [comment]
Everything seems good on my end. Michael just checked on his machine and is working well. I also tested on my machine (locally) and seems to be working fine. We can keep this in mind when we push our final build. @davegregg
